API 14902 GitHub Signin as Guest
department-of-veterans-affairs/lighthouse-developer-portal pull request #605
Opened 2022-04-06 18:54 UTC by keyluck

# Proposed Changes

- Added logic to `Root` that syncs the localStorage with the backend authentication state then reloads the page
  - When the backend is signed in, but the localStorage is signed out the reload will reload the page as a signed in user
  - When the backend is signed out, but the localStorage is signedIn the reload will redirect the user to the login page
- This change fixes the login functionality for any component that calls the `signIn` or `signOut` function with the githubApiRef 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

- [x] My changes generate no new warnings
- [x] Logging has been added where applicable (Error handling, user-driven events, API requests/responses)

- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Tests meet the test coverage threshold

## Reviewer Checklist

- [ ] Is the code easy to understand?
- [ ] Are the changes well documented?

- [ ] Can you think of any use case in which the code does not behave as intended?
- [ ] Can you think of any inputs or external events that could break the code?

- [ ] Should any logging or debugging information be added or removed?

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining how you chose the solution you did and what alternatives you considered, etc...

2022-04-06 20:46 UTC, zaslow requested changes

2022-04-06 20:46 UTC, zaslow commented on packages/app/src/components/Root/Root.tsx
> +    };
I think this would be cleaner for the `subscribe` function:

```ts
if (didCancel) {
  return () => subscription.unsubscribe();
}

if (localStorage.getItem(SIGN_IN_PROVIDER_KEY) ===  'github-auth-provider') {
  if (sessionState === SessionState.SignedIn) {
    localStorage.setItem(SIGN_IN_PROVIDER_KEY, 'github-auth-provider');
  }

  setTimeout(() => window.location.reload());
}

return () => {
  didCancel = true;
  subscription.unsubscribe();
};
```

2022-04-06 20:46 UTC, zaslow commented on packages/app/src/components/Root/Root.tsx
> +            localStorage.setItem(SIGN_IN_PROVIDER_KEY, 'github-auth-provider');
We should pull `github-auth-provider` into a constant

2022-04-06 20:46 UTC, zaslow commented on packages/app/src/components/Root/Root.tsx
> +            setTimeout(() => window.location.reload());
Why do we need to wrap this in `setTimeout`?

2022-04-06 21:19 UTC, keyluck commented on packages/app/src/components/Root/Root.tsx
> +            setTimeout(() => window.location.reload());
We don't, I was having issues with the reload firing after logging in but calling `window.location.reload()` directly seems to work.

2022-04-06 21:27 UTC, keyluck commented on packages/app/src/components/Root/Root.tsx
> +    };
This causes the page to reload constantly when logged in with github

2022-04-11 15:38 UTC, KaemonIsland commented on packages/app/src/components/homepage/index.ts
> +export { AlphaBanner } from './alphabanner/AlphaBanner';
Is there a reason we want to list specific exports vs exporting with `*`?

2022-04-11 15:38 UTC, KaemonIsland approved these changes

2022-04-11 18:24 UTC, closed without merging